language: go
sudo: required

services:
  - docker
 
before_install:
  - docker build -t registry.heroku.com/"$HEROKU_APPNAME"/web .
  - docker login --username=_ --password="$HEROKU_APIKEY" registry.heroku.com
  - docker push registry.heroku.com/"$HEROKU_APPNAME"/web
